# Use an official Python runtime as a parent image
FROM python:3.6-stretch

MAINTAINER  Shirish Kadam <mail@5hirish.com>

# Create directory for static files
RUN mkdir /foobar

# Set the working directory to /app
WORKDIR /foobar

# Copy the current directory contents into the container at /app
COPY . /foobar

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
RUN pip install --default-timeout=3000 --trusted-host pypi.python.org -r requirements.txt

# Define environment variable
# Read from .env file
ENV FLASK_APP /foobar/run_server.py
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Run app when the container launches
CMD celery worker -A foobar.worker.core.celery_task --concurrency=2 -E --loglevel=DEBUG --logfile /foobar/logs/celery.log
