"""empty message

Revision ID: 1b3cbe5a8d6f
Revises: 22e126bce832
Create Date: 2019-07-14 04:07:53.986067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3cbe5a8d6f'
down_revision = '22e126bce832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_description', sa.TEXT(), nullable=True))
    op.add_column('products', sa.Column('product_modified_on', sa.DATE(), nullable=False))
    op.add_column('products', sa.Column('product_name', sa.VARCHAR(length=255), nullable=False))
    op.add_column('products', sa.Column('product_sku', sa.VARCHAR(length=255), nullable=False))
    op.add_column('products', sa.Column('product_status', sa.VARCHAR(length=15), nullable=False))
    op.drop_constraint('erp_products_productSKU_key', 'products', type_='unique')
    op.drop_column('products', 'productStatus')
    op.drop_column('products', 'productDescription')
    op.drop_column('products', 'productSKU')
    op.drop_column('products', 'productModifiedOn')
    op.drop_column('products', 'productName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('productName', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('productModifiedOn', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('productSKU', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('productDescription', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('productStatus', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.create_unique_constraint('erp_products_productSKU_key', 'products', ['productSKU'])
    op.drop_column('products', 'product_status')
    op.drop_column('products', 'product_sku')
    op.drop_column('products', 'product_name')
    op.drop_column('products', 'product_modified_on')
    op.drop_column('products', 'product_description')
    # ### end Alembic commands ###
