"""empty message

Revision ID: 22e126bce832
Revises: d30494d74cc6
Create Date: 2019-05-30 16:24:37.755746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e126bce832'
down_revision = 'd30494d74cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('erp_products', 'productModifiedOn',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint('erp_products_productName_key', 'erp_products', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('erp_products_productName_key', 'erp_products', ['productName'])
    op.alter_column('erp_products', 'productModifiedOn',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
