"""empty message

Revision ID: 6cf304fc97a5
Revises: 
Create Date: 2019-05-30 15:45:16.035303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf304fc97a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_products',
    sa.Column('pid', sa.INTEGER(), nullable=False),
    sa.Column('productName', sa.VARCHAR(length=255), nullable=False),
    sa.Column('productSKU', sa.VARCHAR(length=255), nullable=False),
    sa.Column('productDescription', sa.TEXT(), nullable=True),
    sa.Column('productStatus', sa.VARCHAR(length=15), nullable=False),
    sa.Column('productModifiedOn', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('pid'),
    sa.UniqueConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erp_products')
    # ### end Alembic commands ###
