"""empty message

Revision ID: 9feed11a1928
Revises: 
Create Date: 2019-07-14 06:19:19.367984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9feed11a1928'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_sku', sa.VARCHAR(length=255), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('product_description', sa.TEXT(), nullable=True),
    sa.Column('product_status', sa.VARCHAR(length=15), nullable=False),
    sa.Column('product_modified_on', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('product_sku')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
