"""empty message

Revision ID: d30494d74cc6
Revises: 6cf304fc97a5
Create Date: 2019-05-30 15:47:11.884723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30494d74cc6'
down_revision = '6cf304fc97a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'erp_products', ['productName'])
    op.create_unique_constraint(None, 'erp_products', ['productSKU'])
    op.drop_column('erp_products', 'pid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('erp_products', sa.Column('pid', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'erp_products', type_='unique')
    op.drop_constraint(None, 'erp_products', type_='unique')
    # ### end Alembic commands ###
